### ISSUE TITLE
Add Context in Router

### ISSUE THREAD

**Issue by Feeh03114** [daltonmenezes/electron-router-dom#18]
When I put the context together with all authenticated routes and the screen goes white.

![image](https://github.com/daltonmenezes/electron-router-dom/assets/58147419/a2b3f119-d2b2-4fa1-84f5-4c8fe595d6f5)
![image](https://github.com/daltonmenezes/electron-router-dom/assets/58147419/1d3f8c14-5c68-4e1d-8250-66c1afce35f6)

**Comment by daltonmenezes** [comment]
@Feeh03114 please, can you provide a repo with a minimal example simulating the error?

**Comment by daltonmenezes** [comment]
@Feeh03114 you can take a look at the official [react router dom example](https://github.com/remix-run/react-router/blob/9afac15d8cbe30b37d0f9e8b89c9f1e430dfe35a/examples/auth/src/App.tsx#L43-L46) where the provider is used in the `element` prop, so you can't use it at the same level of a Route, because router dom needs a route, otherwise you get the

```
Error: [AppProvider] is not a <Route> component.
All component children of <Routes> must be a <Route> or <React.Fragment>
```

error!

Example of right usage:
```tsx
<Route
  path="/"
  element={
    <SomeProvider>
      <SomePage />
    </SomeProvider>
  }
/>
```
or you can pass the Router as children of your Provider:
```tsx
<SomeProvider>
  <Router
    main={
      <Route
        path="/"
        element={<SomePage />}
      />
    }
  />
</SomeProvider>
```
